PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?o 
WHERE '{'   
    <{0}> rdf:type skos:Concept .
    <{0}> skos:narrower ?o
'}'
