PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX comete: <http://comete.licef.ca/reference#>

SELECT DISTINCT ?o ?pos
WHERE '{'   
    <{0}> rdf:type skos:Concept .
    <{0}> skos:narrower ?o .
    <{0}> skos:inScheme ?sc .
    ?o skos:inScheme ?sc .
    OPTIONAL '{'
        ?o comete:position ?pos
    '}'
'}'
ORDER BY xsd:integer(?pos)

